### POST to API
POST http://localhost:3000/api/upload/sas
Content-Type: application/json

{
  "fileName": "BraveBrowserSetup-BRV011.exe",
  "fileSize": 104857600,
  "contentType": "application/zip"
}


###